# Pull base image.
FROM ubuntu:18.04

LABEL maintainer="brmather1@gmail.com"
LABEL repo="https://github.com/pyBadlands-workshop"

RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
    build-essential \
    git \
    g++ \
    python-pip \
    python-dev \
    python-zmq \
    pkg-config \
    libfreetype6-dev \
    libpng-dev \
    libopenmpi-dev \
    openmpi-bin \
    libhdf5-dev \
    liblapack-dev \
    llvm-dev \
    libedit-dev \
    gfortran && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


RUN python2 -m pip install --upgrade \
    setuptools \
    pip && \
    python2 -m pip install --upgrade --no-cache-dir \
    Cython==0.20 \
    numpy \
    scipy && \
    python2 -m pip install --no-cache-dir \
    enum34 \
    jupyter \
    markupsafe \
    zmq \
    singledispatch \
    backports_abc \
    certifi \
    jsonschema \
    ipyparallel \
    path.py \
    matplotlib \
    mpi4py==1.3.1 \
    pandas \
    plotly \
    numba==0.23.1 \
    ez_setup \
    gFlex \
    netcdf4==1.3.1 \
    colorlover \
    cmocean \
    scikit-fuzzy \
    pyevtk \
    requests \
    html5lib \
    urllib3 && \
    python2 -m pip install --no-cache-dir \
    llvmlite \
    git+https://github.com/matplotlib/legacycontour.git \
    git+https://github.com/badlands-model/triangle


ENV TINI_VERSION v0.8.4
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/local/bin/tini
RUN chmod +x /usr/local/bin/tini

EXPOSE 8888